CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    email VARCHAR(150) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    iniciales VARCHAR(5),
    nivel VARCHAR(50),
    edad INT,
    sexo VARCHAR(20),
    peso DECIMAL(5,2),
    altura DECIMAL(5,2),
    imc DECIMAL(4,1),
    nivel_actividad VARCHAR(50),
    experiencia VARCHAR(100),
    años_entrenando INT,
    metodologia_preferida VARCHAR(100),
    frecuencia_semanal INT,
    grasa_corporal DECIMAL(5,2),
    masa_muscular DECIMAL(5,2),
    agua_corporal DECIMAL(5,2),
    metabolismo_basal INT,
    cintura DECIMAL(5,2),
    pecho DECIMAL(5,2),
    brazos DECIMAL(5,2),
    muslos DECIMAL(5,2),
    cuello DECIMAL(5,2),
    antebrazos DECIMAL(5,2),
    historial_medico TEXT,
    limitaciones TEXT,
    alergias TEXT,
    medicamentos TEXT,
    objetivo_principal VARCHAR(100),
    meta_peso DECIMAL(5,2),
    meta_grasa DECIMAL(5,2),
    enfoque VARCHAR(100),
    horario_preferido VARCHAR(50),
    comidas_diarias INT,
    suplementacion TEXT,
    alimentos_excluidos TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
